import exception_test
import fib

print(exception_test.greet('Student'))
